### ISSUE TITLE
Failed installation 

### ISSUE THREAD

**Issue by yehudarav** [HermesFlow/pyHermes#50]
Using the noga21 branch: 

` ./install.sh -o ~/Development/HermesFlow2`

Results in 

Git tree HermesFlow/Hermes exist, trying to pull
Already up to date.
Docker image ID: "sha256:ee7e3ecee4ca95bc06f846c18558495605deba2c2827a4b55c6b56cd303b3f0c"
Docker image digest: "[registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0]"
Docker image exists
Docker digest is correct
Docker launch script "docker.sh" generation
Docker launch script "docker_dev.sh" generation
Docker launch script "docker_dev_compile.sh" generation
"/home/yehudaa/Development/HermesFlow2/source" appears to be a git tree, will try to checkout
HEAD is now at 5a352ea639 FEM: solver fenics, fix fenics import test
Hash  0.18-1194-g5a352ea63 wasn't cheked out
Encountered an error, leaving "/home/yehudaa/Development/HermesFlow2"

Any ideas?

**Comment by jackitg** [comment]
Hi Yehuda, 

> "/home/yehudaa/Development/HermesFlow2/source" appears to be a git tree, will try to checkout

checkout of source failed, any un-committed changes in there?
"source" dir exists and is a git tree, is it a clean install? If so, please  clean the destination and retry.
Else: git status of source needs some attention.

**Comment by jackitg** [comment]
Another issue: 

> HEAD is now at 5a352ea639 FEM: solver fenics, fix fenics import test
> Hash 0.18-1194-g5a352ea63 wasn't cheked out

looks like git hash scheme uses and extra digit
I didn't adapt yet to the personal token scheme they require to push, so the local diff is (install.sh:262):
-FREECAD_SOURCE_HASH="0.18-1194-g5a352ea63"
+FREECAD_SOURCE_HASH="0.18-1194-g5a352ea639"

**Comment by yehudarav** [comment]
It failed on clean indtall as well.

**Comment by jackitg** [comment]
is it the one that produced
`Copying /home/yehuda/Development/HeraFlowNoga/Hermes_git/freecad_source_hermes/src to /home/yehuda/Development/HeraFlowNoga/source
docker: Error response from daemon: failed to create shim: OCI runtime create failed: invalid mount {Destination::/mnt/files Type:bind Source:/var/lib/docker/volumes/a552a4adc004e6ab838d7b7e0d541ba289f0a6f3c58bf0c384cdebdcd261eea3/_data Options:[rbind]}: mount
destination :/mnt/files not absolute: unknown.`

at the end?

If so: pls attach the relevant docker sh script that was used to produce this message, 
if not: pls create a new issue, and attach the script to it.

**Comment by yehudarav** [comment]
I changed it to .txt because github did not upload .sh


[install_sh.txt](https://github.com/HermesFlow/Hermes/files/7584124/install_sh.txt)
