### ISSUE TITLE
update all input_parameters

### ISSUE THREAD

**Issue by NogaObs** [HermesFlow/pyHermes#52]
make sure that each node has its own template of input_parametes
implement the new data from FreeCAD - webGui/properties into the input_parametes
(instead of pointing to the source data)

**Comment by NogaObs** [comment]
Hi, 
I just want to make sure the properties of input_parameters for the general nodes
let me know if this is the structure or something need to be changed?

**copy Directory:**
```
"input_parameters": {
            "Source": "",
            "Target": "",
             "dirs_exist_ok" :true
        }
```
do I need to add _dirs_exist_ok_ to FreeCAD properties?

**RunOsCommand:**
```
        "input_parameters": {
            "Method": "",
            "Command": ""
        }
```

**python:**
```
        "input_parameters": {
            "ModulePath": "{Properties.ModulePath.current_val}",
            "ClassName": "{Properties.ClassName.current_val}",
            "MethodName": "{Properties.MethodName.current_val}",
            "Parameters": "{WebGui.formData}"
        }
```

**Comment by yehudarav** [comment]
1. Yes we beed the directory exists.
2. In the python the module path the inputs are the string and not
reference.
Similarly to all the other nodes

**Comment by NogaObs** [comment]
I added a file call HermesGeneral which contain the classes for this specific nodes, including the function that updates the input_parameters.
at the moment it is in a local branch "reOrganize", with all other changes.
(I'm waiting with the merge to "Noga21" branch until we will figure out the problem of loading the webGui)

**Comment by yehudarav** [comment]
Ok.
We tried to instsll it here on a different computer and got similar results
