### ISSUE TITLE
reorganise and clean

### ISSUE THREAD

**Issue by NogaObs** [HermesFlow/pyHermes#53]
1. reorganise the workbench by: mesh, system, constant, etc.
2. update the type of the node to full path - to pydoc.locate
3. clean and remove old files
4. add functions descriptions ''' '''

**Comment by NogaObs** [comment]
I did all the above hopfully.
Another small question - the names of the classes should begin with underscore like **_WebGuiNode**
or without it like **WebGuiNode**

**Comment by yehudarav** [comment]
I think without. Because it isnot neccesarily private

**Comment by NogaObs** [comment]
reorganise the Resources:
```
Resources
    - general
    - openFOAM
            - constant
            - mesh
            - system
                  - controlDict
                        - executers
                        - nodeTemplates
                        - workbench
                  - fvSchemes
                        - executers
                        - nodeTemplates
                        - workbench
    - BC
```

**Comment by NogaObs** [comment]
Hi,
just to make sure that we are on the same page -
1. Those files will be to any node
2. Node name starts with capital letter

![image](https://user-images.githubusercontent.com/62690442/175811910-858e6181-7009-420f-99ba-7684f6aa486e.png)

**Comment by NogaObs** [comment]
Finish rearrange all nodes by: BC, general and openFOAM
The GUI is working.
The executers have not been implemented yet.
