### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by yehudarav** [HermesFlow/pyHermes#84]
./install.sh -o ~/Development/hermes
Cloning into 'Hermes_git'...
Error: No such image: registry.gitlab.com/daviddaish/freecad_docker_env
Docker image ID:
Error: No such image: registry.gitlab.com/daviddaish/freecad_docker_env
Docker image digest:
Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
Error response from daemon: manifest for registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0 not found: manifest unknown: manifest unknown
Docker image pull failed

**Comment by jackitg** [comment]
Hi Yehuda,

The url of the image is wrong now. 
Searching gitlab shows that the user + project are still there. 
Looks like naming scheme changed, will look into more. 

A thought: maybe  we should start basic ubuntu image and reverse-engineer the changes that were done to achieve the equivalent build env (which version of the distribution to start with and so on) . If we manage to pull this, maybe we should produce  our image.

**Comment by yehudarav** [comment]
The main advantage is to be independent of the other repository, right?

The question is if the repo becomes invalid tomorrow,
could we do it then?

Second question.

Is it necessary to upgrade the version of FreeCAD? We will need to upgrade
it
eventually.

**Comment by jackitg** [comment]
Hi Yehuda, I committed an attempt to use "latest" digest. Branch = master. it manages to build here, cannot test atm (my testing machine is in repairs)

Can you please test?

**Comment by yehudarav** [comment]
sure.

**Comment by yehudarav** [comment]
./install.sh -o ../hermes
Cloning into 'Hermes_git'...
Error: No such image: registry.gitlab.com/daviddaish/freecad_docker_env
Docker image ID:
Error: No such image: registry.gitlab.com/daviddaish/freecad_docker_env
Docker image digest:
Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env::latest
docker pull registry.gitlab.com/daviddaish/freecad_docker_env::latest
invalid reference format
Docker image pull failed
Encountered an error, leaving "/home/yehudaa/Development/hermes"

@jackitg

**Comment by jackitg** [comment]
Apologies, a typo slipped in, pls pull and retry

**Comment by yehudarav** [comment]
Hi, 

I got 

[100%] Built target PartDesignGui
If fixing error that do not require qmake, run the following make command:
make -j $(nproc)
root@85cdbd312d7f:~# exit
ERRO[120064] error waiting for container: unexpected EOF 

Is it ok?

**Comment by jackitg** [comment]
Hi Yehuda, 

Yes, looks like it managed complete the build.

**Comment by jackitg** [comment]
Not familiar with the "ERRO[120064] "

**Comment by yehudarav** [comment]
Ok, it might be something local. I will try to run it and see.
